openapi: 3.0.0
info:
  version: 1.0.0
  title: API
paths:
  /v1/upload:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  part:
                    type: integer
                    example: 1
                  etag:
                    type: string
                    example: "a54357aff0632cce46d942af68356b38"
                required:
                  - part
                  - etag
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2058959
                  timestamp:
                    type: integer
                    example: 2058959
                  source:
                    type: string
                    example: 'instagram'
                  folder:
                    type: string
                    example: null
                  height:
                    type: integer
                    example: 1080
                  width:
                    type: integer
                    example: 1080
                  mime:
                    type: string
                    example: "image/jpeg"
                  display:
                    type: object
                    properties:
                      thumbnail:
                        type: object
                        properties:
                          width:
                            type: integer
                            example: 200
                          height:
                            type: integer
                            example: 200
                          src:
                            type: string
                            example: 'https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIGW4VGE1cuYIyIE/image.jpg'
                      preview:
                        type: object
                        properties:
                          width:
                            type: integer
                            example: 800
                          height:
                            type: integer
                            example: 800
                          src:
                            type: string
                            example: 'https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg'
                      square:
                        type: object
                        properties:
                          width:
                            type: integer
                            example: 200
                          height:
                            type: integer
                            example: 200
                          src:
                            type: string
                            example: 'https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg'
                      original:
                        type: object
                        properties:
                          width:
                            type: integer
                            example: 1080
                          height:
                            type: integer
                            example: 1080
                          src:
                            type: string
                            example: 'https://dev-printu-net.s3.eu-central-1.amazonaws.com/photobook/12/7/0/2058959.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAILKHTK5ZOAVQB23Q%2F20180209%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20180209T092316Z&X-Amz-SignedHeaders=host&X-Amz-Expires=518400&X-Amz-Signature=cc95d836e2235992e1948add1bc8f5cdb35d39dc974f8cfa23efd9895db32d38'
                  metadata:
                    type: object
                    properties:
                      gps:
                        type: string
                        example: "52/1, 15/1, 272/100 N 21/1, 1/1, 5851/100 E"
                      datetime:
                        type: integer
                        example: 1516354800
                      name:
                        type: string
                        example: "IMG_9171.JPG"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    example: 400
                  userMessage:
                    type: string
                    example: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
                  devMessage:
                    type: string
                    example: "Check the client_id parameter."
                  more:
                    type: string
                  applicationCode:
                    type: string
                    example: "X1234"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    example: 403
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    example: 404
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    example: 405
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    example: 500
                  userMessage:
                    type: string
                  devMessage:
                    type: string
                  more:
                    type: string
                  applicationCode:
                    type: string
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
